# Excution Environment
executionEnv=local
remoteEnv=BrowserStack



# Adb commands to find appPackage and AppActivity : adb shell dumpsys window | findstr mCurrentFocus


# Android platform details

androidPlatform=Android
androidDeviceName=Samsung Galaxy M33
androidUdid=RZCT912WRAT
androidPlatformVersion=16.0
androidAutomationName=UiAutomator2
androidAppPackage=
androidAppActivity=
#androidAppPath=apps\\android.wdio.native.app.v2.2.0.apk
#androidAppPath=src/test/resources/apps/TheApp.apk
androidAppPath=src/test/resources/apps/ApiDemos-release.apk
appiumUrl=http://127.0.0.1:4723

# Credentials

email=sim8166@gmail.com
pass=Test@12345
wifiName=KumarTower_5G

# iOS Platform

iOSPlatformName=iOS
iOSPlatformVersion=17.0
iOSDeviceName=iPhone15
iOSAutomationName=XCUITest
iOSAppPath=
iOSUDID=

# Browser Stack Details
bsiOSAppPath=bs://1e586d2f38a2d6f2f60ba6759cc5e5d27e26f302
bsiOSDeviceName=
bsUserName=rahulsingh_uWXhLy
bsAccessKey=bcrz7R35LhkqG5JDqKMz

# APIDemos-Release.apk - bs://d123fb57e10e6bc2a5b019ff95ec3c3ae2466261
