# Application Name is Flipboard

# adb command to find the app package and app activity : adb shell dumpsys window | findstr mCurrentFocus

app_package=io.appium.android.apis
app_activity=io.appium.android.apis.ApiDemos
platformName=Android
platformVersion=16.0
deviceName=Samsung Galaxy M33
deviceUdid=RZCT912WRAT
automationName=UiAutomator2
implicit_wait=10
explicit_wait=10
appiumUrl=http://127.0.0.1:4723