############################
# LOCAL ANDROID
############################

androidAppiumUrl=http://127.0.0.1:4723

androidDeviceName=Pixel_6
androidPlatformVersion=14
androidUdid=emulator-5554
androidAutomationName=UiAutomator2
androidAppPath=apps/android.apk



############################
# LOCAL IOS
############################

iOSAppiumUrl=http://127.0.0.1:4725

iOSDeviceName=iPhone 15
iOSPlatformVersion=17
iOSUDID=00008110-000A192E0A12801E
iOSAutomationName=XCUITest
iOSAppPath=apps/ios.app



############################
# BROWSERSTACK
############################

browserstackUserName=YOUR_USERNAME
browserstackAccessKey=YOUR_ACCESS_KEY

# Android
bsAndroidDevice=Samsung Galaxy S23
bsAndroidVersion=14.0
bsAndroidAppId=bs://ANDROID_APP_ID

# iOS
bsIOSDevice=iPhone 15
bsIOSVersion=17
bsIOSAppId=bs://IOS_APP_ID